# Generated by Django 4.0.4 on 2022-05-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myportfolio.editor'),
        ),
    ]
