# Generated by Django 4.0.4 on 2022-05-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_alter_project_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='pro_image',
            field=models.ImageField(null=True, upload_to='index/'),
        ),
    ]
