# Generated by Django 4.0.4 on 2022-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='project/akanname.png', null=True, upload_to='project/'),
        ),
    ]
