# Generated by Django 4.0.4 on 2022-05-27 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_alter_editor_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.editor'),
        ),
    ]
